# Generated by Django 4.2.2 on 2023-06-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0002_alter_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='pic',
            field=models.FileField(default='media/images/mypic.png', upload_to='media/images'),
        ),
        migrations.AddField(
            model_name='societymember',
            name='pic',
            field=models.FileField(default='media/images/mypic.png', upload_to='media/images'),
        ),
    ]
