# Generated by Django 4.2.2 on 2023-06-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0006_eventgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgallery',
            name='videofile',
            field=models.FileField(blank=True, null=True, upload_to='media/videos/', verbose_name=''),
        ),
    ]
